version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: The First Step
         command: |
           chmod a+x ./deploy.sh
           bash ./deploy.sh
           