version: 2.0
jobs:
 build:
   docker:
     - image: alpine:3.7
   steps:
     - run:
         name: Fix ssh Could not resolve hostname # https://stackoverflow.com/a/44046475/9902555
         command: ssh-keyscan $MYSSHHOST >> ~/.ssh/known_hosts # Add production server IP to known hosts.
         
     - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
        fingerprints:
            - "f3:c8:ba:7a:b9:89:88:e4:84:ee:b6:a0:52:4b:23:c8"
     - run:
         name: The First Step
         command: ssh $MYSSHUSER@$MYSSHHOST 'date > /home/$MYSSHUSER/test.txt'
           